In [1]:
#딥러닝
import torch

x_train=torch.Tensor([2,4,6,8,10,12,14,16,18,20]).view(10,1)
y_train=torch.Tensor([0,0,0,0,0,0,1,1,1,1]).view(10,1)

print(x_train.shape,y_train.shape)

C:\Users\ANNA_TEST\anaconda3\Lib\site-packages\torch\cuda\__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


torch.Size([10, 1]) torch.Size([10, 1])


In [2]:
from torch import nn

class MyDeepLearningModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.deepLearningstack=nn.Sequential(
            nn.Linear(1,8),
            nn.Linear(8,1),
            nn.Sigmoid()
        )

    def forward(self, data):
        pred=self.deepLearningstack(data)
        return pred

In [3]:
deepLearning_model=MyDeepLearningModel()

for name, child in deepLearning_model.named_children():
    for param in child.parameters():
        print(name,param)
        

deepLearningstack Parameter containing:
tensor([[-0.9485],
        [-0.2915],
        [ 0.4580],
        [-0.8432],
        [ 0.1640],
        [-0.2325],
        [ 0.8114],
        [ 0.7352]], requires_grad=True)
deepLearningstack Parameter containing:
tensor([ 0.1522, -0.2707,  0.3712, -0.0549,  0.0558,  0.8139,  0.0465,  0.1193],
       requires_grad=True)
deepLearningstack Parameter containing:
tensor([[-0.0802,  0.0221, -0.2988, -0.1314, -0.2308, -0.2364,  0.3447,  0.1657]],
       requires_grad=True)
deepLearningstack Parameter containing:
tensor([0.0089], requires_grad=True)


In [4]:
loss_function=nn.BCELoss()
optimizer=torch.optim.SGD(deepLearning_model.parameters(), lr=1e-1)

In [5]:
nums_epoch=5000

for epoch in range(nums_epoch+1):

    outputs=deepLearning_model(x_train)

    loss=loss_function(outputs, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100==0:
        print('epoch=',epoch,'current_loss=',loss.item())

epoch= 0 current_loss= 1.846045732498169
epoch= 100 current_loss= 0.4021102786064148
epoch= 200 current_loss= 0.31698665022850037
epoch= 300 current_loss= 0.2691454589366913
epoch= 400 current_loss= 0.23731370270252228
epoch= 500 current_loss= 0.21418245136737823
epoch= 600 current_loss= 0.1964132934808731
epoch= 700 current_loss= 0.1822265386581421
epoch= 800 current_loss= 0.17057321965694427
epoch= 900 current_loss= 0.16078615188598633
epoch= 1000 current_loss= 0.15242169797420502
epoch= 1100 current_loss= 0.1451679766178131
epoch= 1200 current_loss= 0.13880161941051483
epoch= 1300 current_loss= 0.13315676152706146
epoch= 1400 current_loss= 0.128106489777565
epoch= 1500 current_loss= 0.12355349957942963
epoch= 1600 current_loss= 0.11942143738269806
epoch= 1700 current_loss= 0.11564888805150986
epoch= 1800 current_loss= 0.11218613386154175
epoch= 1900 current_loss= 0.10899212211370468
epoch= 2000 current_loss= 0.10603348910808563
epoch= 2100 current_loss= 0.1032823696732521
epoch= 220

In [6]:
deepLearning_model.eval()

test_data=torch.Tensor([0.5,3.0,3.5,11.0,13.0,31.0]).view(6,1)

pred=deepLearning_model(test_data)

logical_value=(pred>0.5).float()

print(pred)
print(logical_value)

tensor([[7.2402e-12],
        [1.2468e-09],
        [3.4913e-09],
        [1.7515e-02],
        [5.2295e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])
